### ISSUE TITLE
Server panics over scrypt error.

### ISSUE THREAD

**Issue by GeertJohan** [nulpunt/nulpunt#94]
```
2013/11/02 16:11:19 http: panic serving 127.0.0.1:39629: scrypt: N must be > 1 and a power of 2
goroutine 203 [running]:
net/http.func·007()
    /home/geertjohan/Applications/go/src/pkg/net/http/server.go:1022 +0xac
main.(*AccountDetail).HashPassword(0xc200171ea0, 0xc200199230, 0x4, 0x0, 0xc20016a1f0, ...)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/npserver/account.go:97 +0xf2
main.(*AccountDetail).ValidatePassword(0xc200171ea0, 0xc200199230, 0x4, 0x0)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/npserver/account.go:103 +0x39
main.(*Account).verifyPassword(0xc2001304a0, 0xc200199230, 0x4, 0x0, 0x0, ...)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/npserver/account.go:36 +0x6b
main.(*ClientSession).authenticateAccount(0xc200126f00, 0xc200199228, 0x4, 0xc200199230, 0x4, ...)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/npserver/clientSession.go:173 +0xa3
main.sessionAuthenticateAccountHandlerFunc(0xc2000eff00, 0xc200119540, 0xc200194340)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/npserver/http_sessionHandlers.go:110 +0x3e9
net/http.HandlerFunc.ServeHTTP(0x754028, 0xc2000eff00, 0xc200119540, 0xc200194340)
    /home/geertjohan/Applications/go/src/pkg/net/http/server.go:1149 +0x3e
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2000b1640, 0xc2000eff00, 0xc200119540, 0xc200194340)
    /home/geertjohan/Workspaces/nulpunt/gopath/src/github.com/gorilla/mux/mux.go:90 +0x1e1
net/http.serverHandler.ServeHTTP(0xc200114190, 0xc2000eff00, 0xc200119540, 0xc200194340)
    /home/geertjohan/Applications/go/src/pkg/net/http/server.go:1517 +0x16c
net/http.(*conn).serve(0xc200171d80)
    /home/geertjohan/Applications/go/src/pkg/net/http/server.go:1096 +0x765
created by net/http.(*Server).Serve
    /home/geertjohan/Applications/go/src/pkg/net/http/server.go:1564 +0x266
```

**Comment by GeertJohan** [comment]
Old account didn't have appropriate fields set.
